[variables]
;=========================================;
;===========Nord Color Scheme=============;
;=========================================;

;====Polar Night====;

Nord0=2E3440
Nord1=3B4252
Nord2=434C5E
Nord3=4C566A

;====Snow Storm====;

Nord4=D8DEE9
Nord5=E5E9F0
Nord6=ECEFF4

;====Frost====;

Nord7=8FBCBB
Nord8=88C0D0
Nord9=81A1C1
Nord10=5E81AC

;====Aurora====;

Nord11=BF616A
Nord12=D08770
Nord13=EBCB8B
Nord14=A3BE8C
Nord15=B48EAD