[variables]
;=========================================;
;===========Set These Variables===========;
;=========================================;

;Choose your Weather Location from http://www.weather.com/
WeatherCode=ASXX0016

;Choose your Units: m=Metric, i=Imperial;
WeatherUnit=m

;Set Your Maximum Upload Speed Here;
NetworkMaxUp=10950000

;Set your Maximum Download Speed Here;
NetworkMaxDown=790000

;===========Other===========;
ProcessInterval=5
Substitute="&amp;":"&","&quot;":"","&Quot;":"","&lt;br&gt;":"","![CDATA[":"","]]":"","...":"","<":"",">":"","/PRE&gt;":"","PRE&gt;":"","&lt;":""